name: Terraform CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    environment: rs-owrm

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      - run: terraform init
      - run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    environment: rs-owrm

    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"
    - run: terraform init
    - run: terraform plan -lock-timeout=30s

  terraform-apply:
    runs-on: ubuntu-latest
    environment: rs-owrm

    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"
    - run: terraform init
    - run: terraform apply -auto-approve -lock-timeout=30s
